# Generated by Django 6.0.2 on 2026-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_venta_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='TechPoint POS', max_length=100)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('direccion', models.CharField(default='Milagro, Guayas, Ecuador', max_length=255)),
                ('last_backup', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
