# Generated by Django 6.0.3 on 2026-03-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('ELIMINACION', 'Eliminación'), ('CAMBIO_PRECIO', 'Cambio de Precio'), ('BACKUP', 'Ejecución de Backup'), ('LOGIN', 'Inicio de Sesión')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Adquisición'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='abono',
            name='metodo_pago',
            field=models.CharField(default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta'),
        ),
    ]
