# Generated by Django 6.0.3 on 2026-03-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auditlog_detalleventa_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='email_notificaciones',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
    ]
